name: dsf_video_player
description: "A new Flutter package project."
version: 0.0.1
publish_to: 'none'

ref: &coreversion 9c00e493b2f4bdd5033cabc56765fec59c8a2463

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"
dependency_overrides: 
  video_generator:
    git: 
      url: git@github.com:dreamstock/highlights_generator.git
      ref: 72aeefde05a734cc46dd5e2645d3ab561fae460e
  player_source_models:
    git:
      url: git@github.com:dreamstock/dsf-player-getter.git
      ref: *coreversion 
      path: player_source_models  

  dsf_commum_data_source:
    git:
      url: git@github.com:dreamstock/dsf-player-getter.git
      ref: *coreversion 
      path: dsf_commum_data_source 
  dsf_commum_ref_providers:
    git:
      url: git@github.com:dreamstock/dsf-player-getter.git
      ref: *coreversion 
      path: dsf_commum_ref_providers
  super_native_extensions: 0.8.24
  path_provider: ^2.1.5
  uuid: ^4.4.2
  collection: ^1.19.0
  intl: ^0.20.0

dependencies:
  flutter_svg: ^2.0.17
  dart_debouncer: ^1.1.0
  flutter_portal: ^1.1.4
  youtube_explode_dart: ^2.3.6
  dio: ^5.7.0
  flutter_easyloading: ^3.0.5
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  file_picker: ^8.1.7
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  enchanted_collection: ^1.3.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # media_kit_libs_video: any
  # media_kit_libs_audio: any
  media_kit: ^1.1.11
  media_kit_video: ^1.2.5
  media_kit_libs_android_video: ^1.3.6
  media_kit_libs_ios_video: ^1.1.4
  media_kit_libs_macos_video: ^1.1.4
  media_kit_libs_windows_video: ^1.0.10
  media_kit_libs_linux: ^1.1.3
  video_player_media_kit: ^1.0.5

  video_generator:
    git: 
      url: git@github.com:dreamstock/highlights_generator.git
      ref: 72aeefde05a734cc46dd5e2645d3ab561fae460e 
  player_source_models:
    git:
      url: git@github.com:dreamstock/dsf-player-getter.git
      ref: *coreversion 
      path: player_source_models
  dsf_commum_data_source:
    git:
      url: git@github.com:dreamstock/dsf-player-getter.git
      ref: *coreversion 
      path: dsf_commum_data_source 
  dsf_commum_ref_providers:
    git:
      url: git@github.com:dreamstock/dsf-player-getter.git
      ref: *coreversion 
      path: dsf_commum_ref_providers

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.9.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
